# This file is automatically generated by BioBlender at runtime.
# Modifying it manually might not have an effect.
load C:\Users\Pablo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BioBlender-master\tmp\tmp.pdb
cmd.hide("lines"  ,"tmp")
cmd.set("surface_quality"  ,"1")
cmd.show("surface","tmp")
set solvent_radius,1.399999976158142
cmd.reset()
cmd.origin(position=[0,0,0])
cmd.center("origin")
save C:\Users\Pablo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BioBlender-master\tmp\tmp.wrl
quit